# Generated by Django 5.2.4 on 2025-07-18 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Livraison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('nom_chauffeur', models.CharField(max_length=255)),
                ('client', models.CharField(max_length=255)),
                ('chargements', models.CharField(max_length=255)),
                ('date_chargement', models.DateField()),
                ('date_dechargement', models.DateField()),
                ('bon_livraison', models.CharField(max_length=255)),
                ('tarif', models.CharField(max_length=255)),
                ('deplacement', models.DecimalField(decimal_places=2, max_digits=10)),
                ('avance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('charge_variable', models.DecimalField(decimal_places=2, max_digits=10)),
                ('prix_cv', models.DecimalField(decimal_places=2, max_digits=10)),
                ('operateur', models.CharField(max_length=255)),
                ('commercial', models.CharField(max_length=255)),
                ('ice', models.CharField(max_length=255)),
                ('qte', models.PositiveIntegerField()),
                ('nom_destinataire', models.CharField(max_length=255)),
                ('facturation', models.CharField(max_length=100)),
            ],
        ),
    ]
