# Generated by Django 5.2.4 on 2025-07-18 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('importer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livraison',
            name='timestamp',
            field=models.DateTimeField(unique=True),
        ),
    ]
