# Generated by Django 5.2.4 on 2025-07-18 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('importer', '0002_alter_livraison_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livraison',
            name='date_chargement',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='livraison',
            name='date_dechargement',
            field=models.DateField(blank=True, null=True),
        ),
    ]
