# Generated by Django 5.2.4 on 2025-07-18 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('importer', '0004_alter_livraison_avance_alter_livraison_bon_livraison_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livraison',
            name='date_dechargement',
        ),
        migrations.AddField(
            model_name='livraison',
            name='dechargements',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
