# Generated by Django 5.2.4 on 2025-07-18 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('importer', '0005_remove_livraison_date_dechargement_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='livraison',
            old_name='dechargements',
            new_name='dechargement',
        ),
    ]
